Added new cookbook parse_pdf_docs_for_rag
openai/openai-cookbook pull request #1077
Opened 2024-02-28 13:39 UTC by katia-openai

Added a new cookbook to show how to parse PDF documents for RAG applications.

This PR includes:
- The new cookbook
- Example data used in the cookbook
- Example files generated while executing the cookbook

2024-02-28 17:13 UTC, teomusatoiu requested changes
Intro: i would make this a bit more verbose. Why is this approach good, pros cons anything else worth noting?

Data Preparation: There's a typo "deducted" instead of "dedicated

Setup: /!\ is not displaying correctly for me. Maybe make the writing bold and write Note: instead?
convert_from_bytes is not used - maybe you can remove?

Processing all documents -4th code cell: I would add a disclaimer that it takes ~2 minutes and what are the different stages that you're executing.

Embedding content:
"Adding data such as the slide and deck title or the doc description at the top of each piece of content so that each independent piece is in context" is a bit unclear to me - not sure what you mean here.

"we rely on separators" - why? what separators? how do we do this?

I would also move all imports to the top. I find it a bit cleaner this way.

ModuleNotFoundError: No module named 'rich' -> add to installs

Wrapping up:
I would add some more practical examples - when would you use this? what are good possible usecases for this Cookbook?

Nit but: You have an extra code cell that is empty at the end - i would remove

2024-02-28 17:16 UTC, katia-openai commented on examples/How_to_combine_GPTv_with_RAG_Outfit_Assistant.ipynb
Yep my bad!

2024-02-29 13:24 UTC, teomusatoiu requested changes
Looks good. I think generally i would add a bit more text and explanations to make the flow a bit clearer. Otherwise, i think the content is great! 

Happy to approve once you fix the last few pieces: 
- fixing the GPTv with RAG file (it should not show up as part of this PR)
- last sentence in the conclusion is incomplete.

2024-02-29 13:24 UTC, teomusatoiu commented on examples/How_to_combine_GPTv_with_RAG_Outfit_Assistant.ipynb
It now shows that you've deleted the file. I believe if we merge your PR this file will be deleted on master as well. can you take the master version of this file and put it on your branch as well so there are no "diffs" for it?

2024-02-29 13:24 UTC, teomusatoiu commented on examples/Parse_PDF_docs_for_RAG.ipynb
Wrapping up: last sentence is incomplete: 

You can apply the techniques covered in this notebook to multiple use cases, such as assistants that have access to your proprietary data, customer service or FAQ bots that can read from your internal p

2024-02-29 13:46 UTC, closed without merging