Dylanra/clip based rag
openai/openai-cookbook pull request #1110
Opened 2024-03-19 17:36 UTC by dylanra-openai

## Summary

Adding CLIP embedding RAG.

## Motivation

Showing users how to use multimodal RAG with direct image embeddings

---

## For new content

When contributing new content, read through our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md), and mark the following action items as completed:

- [ ] I have added a new entry in [registry.yaml](https://github.com/openai/openai-cookbook/blob/main/registry.yaml) (and, optionally, in [authors.yaml](https://github.com/openai/openai-cookbook/blob/main/authors.yaml)) so that my content renders on the cookbook website.
- [ ] I have conducted a self-review of my content based on the [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md#rubric):
  - [ ] Relevance: This content is related to building with OpenAI technologies and is useful to others.
  - [ ] Uniqueness: I have searched for related examples in the OpenAI Cookbook, and verified that my content offers new insights or unique information compared to existing documentation.
  - [ ] Spelling and Grammar: I have checked for spelling or grammatical mistakes.
  - [ ] Clarity: I have done a final read-through and verified that my submission is well-organized and easy to understand.
  - [ ] Correctness: The information I include is correct and all of my code executes successfully.
  - [ ] Completeness: I have explained everything fully, including all necessary references and citations.

We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for more details.

2024-03-28 14:35 UTC, ibigio requested changes
| Criteria     | Description                                                                                         | Score |
| ------------ | --------------------------------------------------------------------------------------------------- | ----- |
| Relevance    | Is the content related to building with OpenAI technologies? Is it useful to others?                |    4   |
| Uniqueness   | Does the content offer new insights or unique information compared to existing documentation?       |     4  |
| Clarity      | Is the language easy to understand? Are things well-explained? Is the title clear?                  |     2  |
| Correctness  | Are the facts, code snippets, and examples correct and reliable? Does everything execute correctly? |    4   |
| Conciseness  | Is the content concise? Are all details necessary? Can it be made shorter?                          |     3  |
| Completeness | Is the content thorough and detailed? Are there things that weren’t explained fully?                |    4   |
| Grammar      | Are there grammatical or spelling errors present?                                                   |     3  |

Thanks for writing this up! The topic is super useful, excited to see share this. Left a few comments – generally this cookbook needs some work on structure and clarity (e.g. use of sections and headings, high-level explanations before jumping into details, and some splitting out / refactoring of code blocks).

Happy to take another look after a pass at these – this is super useful content!

2024-03-28 14:35 UTC, ibigio commented on examples/custom_image_embedding_search.ipynb
> +        "The application area we will use to bring this technique to life is performing RAG over user inputted images of technology and searching our enterprise knowledge base for a matching image to
This context is useful but could be shortened and rephrased a bit – (sharing the ChatGPT prompt I use below)
```
Condense the following text, while keeping the word choice and tone the same.
```

2024-03-28 14:35 UTC, ibigio commented on examples/custom_image_embedding_search.ipynb
> +      "execution_count": 44,
nit: Make sure to re-run your file in order so these are sequential and consecutive

2024-03-28 14:35 UTC, ibigio commented on examples/custom_image_embedding_search.ipynb
> +        "import faiss"
These are lots os standard packages mixed with specific utils. Might want to split out the "meat" (openai, faiss, torch) from the standard (json, os, etc) and the specific/viz (matplotlib, tqdm, etc). And for the "meat" ones, would be useful to explain what you'll be using each one for, at a very high level.

2024-03-28 14:35 UTC, ibigio commented on examples/custom_image_embedding_search.ipynb
> +        "device = \"cpu\"\n",
nit: comment on what this is (i'm assuming cpu vs gpu?)

2024-03-28 14:35 UTC, ibigio commented on examples/custom_image_embedding_search.ipynb
> +        "### Installations and imports\n",
nit: use single # for top-level headers
(also see comment about explaining why you're install certain packages/imports below)

2024-03-28 14:35 UTC, ibigio commented on examples/custom_image_embedding_search.ipynb
> +        "Now let's load the CLIP model."
Add a section header. Would also be helpful to explain the steps you'll be taking throughout the cookbook at a high-level here (briefly) so the reader knows what's coming and what to expect.

2024-03-28 14:35 UTC, ibigio commented on examples/custom_image_embedding_search.ipynb
> +      "source": [
i'd split this up into separate code blocks, and put your longer comment explanations as text before. then you can give the tricky bits more space (and comments) e.g. get_features_from_image_path

2024-03-28 14:35 UTC, ibigio commented on examples/custom_image_embedding_search.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAigAAAF9CAYAAAAuppNcAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQ
inquire*

2024-03-28 14:35 UTC, ibigio commented on examples/custom_image_embedding_search.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAigAAAF9CAYAAAAuppNcAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQ
nit: add conclusion paragraph

2024-03-28 14:35 UTC, ibigio commented on examples/custom_image_embedding_search.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAf0AAAGiCAYAAADtFB+qAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQ
put image in images folder, add reference here (examples in [assistants cookbook](https://cookbook.openai.com/examples/assistants_api_overview_python))

2024-04-09 17:31 UTC, ibigio approved these changes
Thanks for incorporating the feedback! Left a few comments for minor typos, etc. Final note is to consider a title like "Multimodal RAG with CLIP Embeddings and GPT-4 Vision". Excited for this to ship!

2024-04-10 12:02 UTC, merged

2024-08-10 22:26 UTC, Androbin commented on examples/custom_image_embedding_search.ipynb
> +        "%pip install clip\n",
Are you sure this is the right package?
https://pypi.org/project/clip/