Function call cookbook
openai/openai-cookbook pull request #1213
Opened 2024-05-14 22:03 UTC by msingh-openai

## Summary

Update function call cookbook with latest model and API specifications 

## Motivation

The function call cook book updated to newer model 'GPT-4o' and used the latest API specification to invoke the Chat Completions API with "role":"tool" (rather than using "role":"function")

2024-05-15 10:46 UTC, teomusatoiu requested changes
Looks good! thanks for the contribution! I made a few small comments but once they're resolved it's good to ship!

2024-05-15 10:46 UTC, teomusatoiu commented on examples/How_to_call_functions_with_chat_models.ipynb
> +   "execution_count": 62
can you re-run all cells so they're nicely numbered starting from 1?

2024-05-15 10:46 UTC, teomusatoiu commented on examples/How_to_call_functions_with_chat_models.ipynb
> +    "Step #3: . Extract the function name and parameters from response, call the function with parameters. Append the result to messages.    \n",
there's an extra dot here

2024-05-15 10:46 UTC, teomusatoiu commented on examples/How_to_call_functions_with_chat_models.ipynb
> +    "##### Steps to invoke a function call using Chat Completions API: \n",
Nit but could you make this a little bit more readable? Say add some bold for Step 1, Step 2 etc. I think you can also remove the '#' signs.

2024-05-15 17:49 UTC, msingh-openai commented
All comments addressed! Thanks for reviewing :)

2024-05-17 08:20 UTC, teomusatoiu approved these changes
Looks good! Approved!

2024-05-17 08:20 UTC, merged