Update readme, include LlamaIndex
openai/openai-cookbook pull request #457
Opened 2023-05-25 18:43 UTC by jerryjliu

2023-05-25 19:58 UTC, ted-at-openai requested changes
The link is broken, due the space between [] ().

2023-05-25 22:14 UTC, jerryjliu commented
@ted-at-openai thanks, added!

2023-06-01 22:45 UTC, ted-at-openai approved these changes

2023-06-01 22:45 UTC, merged

2023-06-01 22:45 UTC, ted-at-openai commented
Thanks for the contribution!