Add AwaDB to Vector Database notebooks
openai/openai-cookbook pull request #644
Opened 2023-08-17 13:56 UTC by taozhiwang

Hi!

This pr adds a new notebook that provides an example of using Openai API and AwaDB for QA tasks.

It contains:
 - Use Openai Embedding to embed texts and save them to AwaDB
 - Do a similarity search
 - Automated prompt generation based on search results
 - Use Openai API to do question answering

2023-08-17 15:26 UTC, janfilips reviewed
Looks good..

2023-08-23 13:53 UTC, taozhiwang commented
Hi @simonpfish, can you review this pr for me? Thanks for your time!

2023-08-29 01:16 UTC, simonpfish commented
taking a look! thanks for the contribution

2023-08-29 01:20 UTC, simonpfish commented on examples/vector_databases/AwaDB/Using_AwaDB_for_Question_Answering_tasks.ipynb
> +    "This notebook is an example for how you can use AwaDB as the vector database to save embedding gained from OpenAI Embedding. Then use GPT and embedding-based search to do question answering task
```suggestion
    "This notebook demonstrates how to utilize AwaDB as a vector database for storing embeddings obtained from OpenAI. It then illustrates how to employ GPT and embedding-based search for question answering tasks.\n",
```

2023-08-29 01:21 UTC, simonpfish commented on examples/vector_databases/AwaDB/Using_AwaDB_for_Question_Answering_tasks.ipynb
> +    "We will provide an end-to-end workflow example to illustrate the entire process.\n",
```suggestion
    "We outline an end-to-end workflow example to illustrate the entire process.\n",
```

2023-08-29 01:23 UTC, simonpfish requested changes
there are lots of misspellings and grammatical errors across the notebook. i'd suggest giving it a polish pass and then resubmitting

2023-08-29 22:21 UTC, closed without merging