#636
openai/openai-cookbook pull request #645
Opened 2023-08-21 19:50 UTC by vishveshjain

2023-08-21 20:23 UTC, vishveshjain commented
This omits *characters*, not *lines* from the file names. #635

2023-08-29 01:14 UTC, simonpfish commented
thanks for the contribution. can you be a bit more specific about what you're trying to achieve here? and perhaps title the PR more explicitly?

2023-08-29 01:15 UTC, simonpfish requested changes

2023-08-29 17:40 UTC, simonpfish commented
closing in favor of #636

2023-08-29 17:40 UTC, closed without merging