Update Elastic cloud signup url
openai/openai-cookbook pull request #726
Opened 2023-09-19 18:01 UTC by saarikabhasi

## PR Summary

This PR updates  Elastic cloud sign up url in Elasticsearch Vector Database example [notebooks](https://github.com/openai/openai-cookbook/tree/main/examples/vector_databases/elasticsearch) with `utm_source` & `utm_content` fields.

2023-09-22 17:49 UTC, shyamal-anadkat approved these changes
lgtm, thanks!

2023-09-26 23:26 UTC, simonpfish requested changes
Are these python version changes intentional?

2023-09-26 23:26 UTC, simonpfish commented on examples/vector_databases/elasticsearch/elasticsearch-retrieval-augmented-generation.ipynb
> +   "version": "3.11.4"
is this change intentional?

2023-09-26 23:26 UTC, simonpfish commented on examples/vector_databases/elasticsearch/elasticsearch-semantic-search.ipynb
> +   "version": "3.11.4"
likewise here

2023-09-27 23:01 UTC, simonpfish commented on examples/vector_databases/elasticsearch/elasticsearch-retrieval-augmented-generation.ipynb
> +   "version": "3.11.4"
```suggestion
   "version": "3.10.12"
```

2023-09-27 23:01 UTC, simonpfish commented on examples/vector_databases/elasticsearch/elasticsearch-semantic-search.ipynb
> +   "version": "3.11.4"
```suggestion
   "version": "3.10.12"
```

2023-09-27 23:02 UTC, simonpfish approved these changes

2023-09-27 23:02 UTC, merged

2023-09-28 07:43 UTC, joemcelroy commented
thank you!