Adding litellm to relevant resources
openai/openai-cookbook pull request #757
Opened 2023-10-03 22:42 UTC by krrishdholakia

Adding litellm to relevant resources

2023-10-03 22:44 UTC, krrishdholakia commented
cc: @simonpfish

2023-10-04 01:07 UTC, simonpfish requested changes
Nice, thanks for contributing to our related resources!

I think it's important that you phrase this description here around the actual utility that this library gives to developers, and not just the fact that it can call many LLM APIs. Langchain, Haystack, LLamaIndex can all already do that. What differentiates LiteLLM?

I would suggest perhaps also updating the phrasing in your repo's description to be more inclusive and not about replacing OpenAI. I like the framing in your README slightly better "Call all LLM APIs using the OpenAI format"

![CleanShot 2023-10-03 at 18 07 34@2x](https://github.com/openai/openai-cookbook/assets/8716950/ca6ce3e4-684c-4a75-b86b-7e892d53aa13)

2023-10-04 01:17 UTC, krrishdholakia commented on related_resources.md
> +- [🚅 LiteLLM](https://github.com/BerriAI/litellm): Easily call Anthropic/Huggingface/etc. using the OpenAI format
is that a requirement? This is a pretty consistent part of our branding, and I'd prefer to keep it.

2023-10-04 01:17 UTC, krrishdholakia commented
Update made @simonpfish 
<img width="531" alt="Screenshot 2023-10-03 at 6 17 34 PM" src="https://github.com/openai/openai-cookbook/assets/17561003/7d8a36cb-e966-4d1e-8608-2e922a80b430">

2023-10-04 17:30 UTC, krrishdholakia commented
Bump on this @simonpfish

2023-10-04 18:28 UTC, simonpfish commented on related_resources.md
> +- [🚅 LiteLLM](https://github.com/BerriAI/litellm): Easily call Anthropic/Huggingface/etc. using the OpenAI format
Yes that's a requirement. We don't want to give preferential treatment to any library, and emojis stand out.

2023-10-04 18:29 UTC, simonpfish commented
I'm waiting for you to answer my previous question:

> I think it's important that you phrase this description here around the actual utility that this library gives to developers, and not just the fact that it can call many LLM APIs. Langchain, Haystack, LLamaIndex can all already do that. What differentiates LiteLLM?

2023-10-04 18:33 UTC, krrishdholakia commented
I thought i did that by updating the description based on the one you recommended - 
<img width="883" alt="Screenshot 2023-10-04 at 11 33 20 AM" src="https://github.com/openai/openai-cookbook/assets/17561003/9aec9948-e68d-4bf3-9ce4-8baf8530bffd">
<img width="421" alt="Screenshot 2023-10-04 at 11 33 29 AM" src="https://github.com/openai/openai-cookbook/assets/17561003/980a9e7e-a123-4e9a-9eea-8bd82901d198">

is there another place where the change was required?

2023-10-04 18:34 UTC, krrishdholakia commented on related_resources.md
> +- [🚅 LiteLLM](https://github.com/BerriAI/litellm): Easily call Anthropic/Huggingface/etc. using the OpenAI format
ok - updated.

2023-10-04 19:05 UTC, krrishdholakia commented
@simonpfish LiteLLM doesn't compete with Langchain, LlamaIndex etc. We actually have integrations with both of them: 
- https://python.langchain.com/docs/integrations/chat/litellm
- https://docs.llamaindex.ai/en/latest/examples/llm/litellm.html

These were because of community requests - e.g.: https://github.com/run-llama/llama_index/issues/7458

We built this library because nothing solves the consistent model I/O problem that exists when you go cross-provider. 

LiteLLM makes it easy for you to call different LLM APIs with a consistent input-output format (i.e. the OpenAI format). 

Please let me know what is unclear here.

2023-10-04 19:23 UTC, simonpfish commented on related_resources.md
> +- [LiteLLM](https://github.com/BerriAI/litellm): Easily call Anthropic/Huggingface/etc. using the OpenAI format
```suggestion
- [LiteLLM](https://github.com/BerriAI/litellm): Minimal Python library that allows you to call various LLM APIs with a consistent format. 
```

2023-10-04 19:23 UTC, simonpfish commented
Got it. Just suggested some updates to the description to better capture this.

2023-10-04 20:20 UTC, krrishdholakia commented
Updated based on feedback, are there any remaining blockers for merge @simonpfish

2023-10-04 22:09 UTC, simonpfish commented
Rather than using an imperative sentence, let's use the same descriptive format as all the other resources listed. For example, "A Python library that allows you to..."

2023-10-04 22:37 UTC, krrishdholakia commented
Done @simonpfish. Any remaining blockers for merge

2023-10-05 17:53 UTC, krrishdholakia commented
bump on this @simonpfish

2023-10-05 17:55 UTC, simonpfish commented
No need for all the bumps. This is on my queue and I'll get to it as soon as I can. We're all busy people, no need to spam our inboxes.

2023-10-05 18:01 UTC, simonpfish commented on related_resources.md
> +- [LiteLLM](https://github.com/BerriAI/litellm): A Python library to call various LLM APIs (OpenAI/Azure/Huggingface/etc.) using the OpenAI format
```suggestion
- [LiteLLM](https://github.com/BerriAI/litellm): A minimal Python library for calling LLM APIs with a consistent format. 
```

2023-10-05 18:02 UTC, simonpfish commented
Added a period and modified the wording to be more descriptive and general.

2023-10-05 18:03 UTC, merged

2023-10-05 18:26 UTC, krrishdholakia commented
Thanks @simonpfish 

I don't see it yet. Is there a delay before it's live? 
<img width="1328" alt="Screenshot 2023-10-05 at 11 26 46 AM" src="https://github.com/openai/openai-cookbook/assets/17561003/dedf22b8-77f7-46bd-9d04-a37df8626f90">