Update registry.yaml to add Weights & Biases examples
openai/openai-cookbook pull request #758
Opened 2023-10-04 13:53 UTC by ash0ts

## Summary

Update registry.yaml to add Weights & Biases examples for the cookbook website.

## Changes

Update registry.yaml

- Major Changes
  - Update registry.yaml to add Weights & Biases examples

## Motivation

Discoverability on the more popularly rendered website

## Self Review Checklist

- [ ] Is the writing easily skimmable?
  - Sections have informative titles.
  - Key takeaways are upfront.
  - Short paragraphs and topic sentences are used.
- [ ] Is the writing quality high?
  - Sentences are simple and unambiguous.
  - Demonstrative pronouns are avoided or clearly referenced.
  - No left-branching sentences.
- [ ] Is the content universally helpful?
  - Terminology is specific and avoids jargon.
  - Provides solutions to common problems.
  - Code examples are general and exportable.
- [ ] Is the content consistent?
  - Styling and formatting align with existing documentation.
  - Consistent use of punctuation and case.

When contributing a new example, make sure to add a new entry for it in [registry.yaml](/registry.yaml) to render it on the cookbook website.

**Note:** For additional guidelines on writing good documentation, check out [What Makes Documentation Good](https://cookbook.openai.com/what_makes_documentation_good).

2023-10-04 13:54 UTC, ash0ts commented
@simonpfish I forgot to update the `registry.yaml`. Would appreciate a stamp

2023-10-04 18:23 UTC, simonpfish requested changes
Just one minor comment!

2023-10-04 18:23 UTC, simonpfish commented on registry.yaml
> +    - ash0ts
was this intentional? 

```suggestion
    - FayazRahman
```

2023-10-04 18:24 UTC, simonpfish commented on registry.yaml
> +- title: OpenAI API Monitoring with W&B Weave
Let's maybe include the full name here for clarity at the top level. 

```suggestion
- title: OpenAI API Monitoring with Weights & Biases Weave
```

2023-10-05 11:29 UTC, ash0ts commented
@simonpfish Added the suggestions you made. One nit, I called the `Finetuning example`: `Fine-tuning GPT with Weights & Biases`

2023-10-05 18:04 UTC, simonpfish commented
Perfect! Merging.

2023-10-05 18:04 UTC, merged