matching new spec for recipe
openai/openai-cookbook pull request #837
Opened 2023-11-09 22:18 UTC by jhills20

## Summary

Briefly describe the changes and the goal of this PR. Make sure the PR title summarizes the changes effectively.
Updates for spec + GPT Vision preview rate limit
## Motivation

Why are these changes necessary? How do they improve the cookbook?
So these recipes can run with new spec
---

## For new content

When contributing new content, read through our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md), and mark the following action items as completed:

- [ ] I have added a new entry in [registry.yaml](/registry.yaml) (and, optionally, in [authors.yaml](/authors.yaml)) so that my content renders on the cookbook website.
- [ ] I have conducted a self-review of my content based on the [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md#rubric):
  - [ ] Relevance: This content is related to building with OpenAI technologies and is useful to others.
  - [ ] Uniqueness: I have searched for related examples in the OpenAI Cookbook, and verified that my content offers new insights or unique information compared to existing documentation.
  - [ ] Spelling and Grammar: I have checked for spelling or grammatical mistakes.
  - [ ] Clarity: I have done a final read-through and verified that my submission is well-organized and easy to understand.
  - [ ] Correctness: The information I include is correct and all of my code executes successfully.
  - [ ] Completeness: I have explained everything fully, including all necessary references and citations.

We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for more details.

2023-11-10 17:12 UTC, simonpfish approved these changes

2023-11-10 17:12 UTC, simonpfish commented on examples/Function_calling_finding_nearby_places.ipynb
> +   "execution_count": 36,
When submitting notebooks, it's generally a good idea to restart the kernel and run from scratch to reset the execution counts and make sure it all runs well in order

2023-11-10 17:15 UTC, simonpfish requested changes
Oh actually, I'm seeing this error in the notebook, do you think we could get rid of it? 

![CleanShot 2023-11-10 at 12 13 19@2x](https://github.com/openai/openai-cookbook/assets/8716950/bb5b1021-8932-46c7-88d2-8d991f218d43)

2023-11-13 03:38 UTC, jhills20 commented
> Oh actually, I'm seeing this error in the notebook, do you think we could get rid of it?
> 
> ![CleanShot 2023-11-10 at 12 13 19@2x](https://user-images.githubusercontent.com/8716950/282131793-bb5b1021-8932-46c7-88d2-8d991f218d43.png)

fixed

2023-11-14 21:30 UTC, simonpfish approved these changes

2023-11-14 21:31 UTC, merged