Added token calculation using tiktoken for gpt 4 vision and code update for latest version 1.3.5
openai/openai-cookbook pull request #881
Opened 2023-11-23 16:37 UTC by RamishRasool14

## Summary

Briefly describe the changes and the goal of this PR. Make sure the PR title summarizes the changes effectively.
* Added token calculation using tiktoken for gpt 4 vision for both image urls and base64 images
* Modified code to support latest version of openai 1.3.5
## Motivation

Why are these changes necessary? How do they improve the cookbook?
* Previously there was no support for input image prompt token calculation
* The code was using older version of openai which was incorrect when executed using latest version
---

## For new content

When contributing new content, read through our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md), and mark the following action items as completed:

- [x] I have added a new entry in [registry.yaml](/registry.yaml) (and, optionally, in [authors.yaml](/authors.yaml)) so that my content renders on the cookbook website.
- [x] I have conducted a self-review of my content based on the [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md#rubric):
  - [x] Relevance: This content is related to building with OpenAI technologies and is useful to others.
  - [x] Uniqueness: I have searched for related examples in the OpenAI Cookbook, and verified that my content offers new insights or unique information compared to existing documentation.
  - [x] Spelling and Grammar: I have checked for spelling or grammatical mistakes.
  - [x] Clarity: I have done a final read-through and verified that my submission is well-organized and easy to understand.
  - [x] Correctness: The information I include is correct and all of my code executes successfully.
  - [x] Completeness: I have explained everything fully, including all necessary references and citations.

We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for more details.

2023-11-27 21:53 UTC, simonpfish requested changes
This is awesome, thanks! 

A couple of small comments.

2023-11-27 21:53 UTC, simonpfish commented on registry.yaml
> +- title: GPT-4 vision image token calculation using TikToken
We already have an entry for `examples/How_to_count_tokens_with_tiktoken.ipynb`

If you want this to be a new entry, we should split it into its own notebook.

2023-11-27 21:53 UTC, simonpfish commented on examples/How_to_count_tokens_with_tiktoken.ipynb
> +    "import math\n",
Could be nice to add a text cell above explaining what's happening here and citing the docs.

2023-12-13 06:49 UTC, dongmingli-Ben commented
Several new models came out in the last month, including gpt-4-1106-preview. It would be nice to update the token counting example to include these new models.

2024-02-23 01:46 UTC, closed without merging